### ISSUE TITLE
Cannot decode a lightning invoice without amount

### ISSUE THREAD

**Issue by bjarnemagnussen** [fiatjaf/ln-decodepay#1]
When parsing a lightning invoice that does not have a value assigned to it, such as e.g.: `lnbc1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqdpl2pkx2ctnv5sxxmmwwd5kgetjypeh2ursdae8g6twvus8g6rfwvs8qun0dfjkxaq8rkx3yf5tcsyz3d73gafnh3cax9rn449d9p5uxz9ezhhypd0elx87sjle52x86fux2ypatgddc6k63n7erqz25le42c4u4ecky03ylcqca784w`, the function `DecodepayWithCurrency` breaks.

The reason is that `DecodepayWithCurrency` expects the value of `inv.MilliSat` to contain a pointer to a bitcoin amount, which however will contain a pointer to `nil` when no value is specified in the lightning invoice.

**Comment by fiatjaf** [comment]
Can we just make it zero if that pointer is `nil`?

**Comment by bjarnemagnussen** [comment]
I think so!

BTW: The same issue arises with the description field. It may be missing from the lightning invoice such as e.g. here:
`lntb20m1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqsfpp3x9et2e20v6pu37c5d9vax37wxq72un98k6vcx9fz94w0qf237cm2rqv9pmn5lnexfvf5579slr4zq3u8kmczecytdx0xg9rwzngp7e6guwqpqlhssu04sucpnz4axcv2dstmknqq6jsk2l`

`DecodepayWithCurrency()` then fails because the `inv.Description` pointer is nil.

**Comment by fiatjaf** [comment]
Do you want to submit a fix? :nerd_face: 
Please!

**Comment by bjarnemagnussen** [comment]
With pleasure! I will look into it tomorrow and submit a small PR :)
